[package]
name = "helloween"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
bincode = "1.3.3"
futures-util = { version = "0.3.29", features = ["sink"] }
k256 = { version = "0.13.1", features = ["serde"] }
serde = { version = "1.0.190", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.33.0", features = ["full"] }
